# Generated by Django 3.2.13 on 2022-07-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='photo',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
