# Generated by Django 3.2.13 on 2022-07-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20220708_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
