# Generated by Django 3.2.13 on 2022-07-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_pokemon_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='discription',
            new_name='description',
        ),
    ]
