# Generated by Django 3.2.13 on 2022-07-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_pokemon_evolution_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='evolution_from',
            new_name='previous_evolution',
        ),
    ]
